# Site settings
title: Moritz Schüler
email: moritz-schueler96@gmx.de
description: > # this means to ignore newlines until "baseurl:"
   Graduate computer science student at Technical University Munich. I focus on machine learning and deep learning applications.
baseurl: "" # the subpath of your site, e.g. /blog
url: https://moritzschueler96.github.io # the base hostname & protocol for your site moritz-schueler.de
production_url: "https://moritzschueler96.github.io"
github_username: moritzschueler96
permalink: /blog/:year/:month/:title.html

twitter:
  username: SchuelerMo

sass:
  style: compressed

collections:
  publications:
    output: false

jekyll-mentions:
  base_url: https://twitter.com

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-mentions
